<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1531" started-at="2020-06-27T12:32:44Z" finished-at="2020-06-27T12:32:45Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1531" started-at="2020-06-27T12:32:44Z" finished-at="2020-06-27T12:32:45Z">
      <class name="MySuvidha.in.TestCases.SignUpTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:MySuvidha.in.TestCases.SignUpTest@2767e23c]" name="setUp" is-config="true" duration-ms="26954" started-at="2020-06-27T18:02:17Z" finished-at="2020-06-27T18:02:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="signUpTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:MySuvidha.in.TestCases.SignUpTest@2767e23c]" name="signUpTest" duration-ms="767" started-at="2020-06-27T18:02:44Z" data-provider="CommonDP" finished-at="2020-06-27T18:02:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Gulab]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Mali]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[9584841130]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[gulab@mali]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at MySuvidha.in.base.TestBase.type(TestBase.java:172)
	at MySuvidha.in.TestCases.SignUpTest.signUpTest(SignUpTest.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUpTest -->
        <test-method status="FAIL" signature="signUpTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:MySuvidha.in.TestCases.SignUpTest@2767e23c]" name="signUpTest" duration-ms="146" started-at="2020-06-27T18:02:45Z" data-provider="CommonDP" finished-at="2020-06-27T18:02:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Bhawna]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Mali]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[9538740876]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[mali@132456]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at MySuvidha.in.base.TestBase.type(TestBase.java:172)
	at MySuvidha.in.TestCases.SignUpTest.signUpTest(SignUpTest.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUpTest -->
        <test-method status="FAIL" signature="signUpTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:MySuvidha.in.TestCases.SignUpTest@2767e23c]" name="signUpTest" duration-ms="49" started-at="2020-06-27T18:02:45Z" data-provider="CommonDP" finished-at="2020-06-27T18:02:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[T]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[karki]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[9584841160]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[password1234]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at MySuvidha.in.base.TestBase.type(TestBase.java:172)
	at MySuvidha.in.TestCases.SignUpTest.signUpTest(SignUpTest.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUpTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:MySuvidha.in.TestCases.SignUpTest@2767e23c]" name="tearDown" is-config="true" duration-ms="4716" started-at="2020-06-27T18:02:46Z" finished-at="2020-06-27T18:02:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- MySuvidha.in.TestCases.SignUpTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
